//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tabl
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public string Passworde { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Phone_Number { get; set; }
        public string City { get; set; }
    }
}
